# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'TuneUpPlistToJunit/version'

Gem::Specification.new do |spec|
  spec.name = 'tuneup-plist-to-junit'
  spec.version = TuneUpPlistToJunit::VERSION
  spec.authors = ['Vincent Pizzo']
  spec.email = %w(vincent.pizzo@singlewire.com)
  spec.description = %q{Processes a UIAutomation Plist file as generated by tuneup.js into a JUnit format}
  spec.summary = %q{Processes a UIAutomation Plist file as generated by tuneup.js into a JUnit format. Used so it can easily be parsed by CI such as Jenkins.}
  spec.homepage = 'http://github.com/vincentjames501/TuneUpPlistToJunit'
  spec.license = 'MIT'

  spec.files = `git ls-files`.split($/)
  spec.executables = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = %w(lib)

  spec.add_dependency 'plist', '~> 3.1.0'
  spec.add_dependency 'nokogiri', '~> 1.6.1'

  spec.add_development_dependency 'bundler', '~> 1.3'
  spec.add_development_dependency 'rake'
  spec.add_development_dependency 'rspec', '~> 2.14.1'
end
